server:
    port: 8080
#    ssl:
#      key-store: classpath:client.jks
#      key-store-password: s3cr3t  
#      key-password: s3cr3t
#      trust-store: classpath:client.jks
#      trust-store-password: s3cr3t
#      client-auth: need
ssltest:
  key-store: classpath:client.jks
  key-store-password: s3cr3t 
  key-password: s3cr3t 
  trust-store: classpath:client-trust.jks
  trust-store-password: s3cr3t
